import 'dart:async';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../../core/theme/app_theme.dart';
import '../../services/trail_unlock_service.dart';

/// Scans a trail-authorization QR code (generated by app_geo). A valid scan
/// unlocks the "Démarrer" button for that trail; an invalid one shows an error
/// code inviting the user to contact the administrator.
class QrUnlockScreen extends StatefulWidget {
  const QrUnlockScreen({super.key});

  @override
  State<QrUnlockScreen> createState() => _QrUnlockScreenState();
}

class _QrUnlockScreenState extends State<QrUnlockScreen>
    with WidgetsBindingObserver {
  final MobileScannerController _controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
  );
  bool _handling = false;
  String? _startError;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    // mobile_scanner v5 no longer auto-starts the camera — do it manually.
    _start();
  }

  Future<void> _start() async {
    try {
      await _controller.start();
      if (mounted && _startError != null) {
        setState(() => _startError = null);
      }
    } catch (e) {
      if (mounted) {
        setState(() => _startError =
            'Impossible d\'ouvrir la caméra. Autorisez l\'accès caméra dans '
            'les réglages, puis réessayez.');
      }
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // Keep the camera in sync with the app lifecycle (required in v5).
    if (_handling) return;
    switch (state) {
      case AppLifecycleState.resumed:
        unawaited(_controller.start().catchError((_) {}));
        break;
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
        unawaited(_controller.stop().catchError((_) {}));
        break;
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _controller.dispose();
    super.dispose();
  }

  Future<void> _onDetect(BarcodeCapture capture) async {
    if (_handling) return;
    final raw = capture.barcodes
        .map((b) => b.rawValue)
        .firstWhere((v) => v != null && v.isNotEmpty, orElse: () => null);
    if (raw == null) return;

    setState(() => _handling = true);
    await _controller.stop();

    final result = await TrailUnlockService.instance.redeem(raw);
    if (!mounted) return;

    if (result.isSuccess) {
      await _showSuccessDialog(result.trailName ?? '');
      if (mounted) Navigator.of(context).pop(true);
    } else {
      await _showErrorDialog(result.errorCode ?? 'ERR-QR');
      if (mounted) {
        setState(() => _handling = false);
        await _controller.start();
      }
    }
  }

  Future<void> _showSuccessDialog(String trailName) {
    return showDialog<void>(
      context: context,
      builder: (ctx) => AlertDialog(
        icon: const Icon(Icons.verified, color: AppTheme.primaryColor, size: 40),
        title: const Text('Sentier déverrouillé'),
        content: Text(
          trailName.isEmpty
              ? 'Le bouton « Démarrer » est activé pour ce sentier pendant '
                  '24 heures. Au-delà, il faudra un nouveau QR de l\'admin.'
              : 'Le bouton « Démarrer » est activé pour « $trailName » pendant '
                  '24 heures. Au-delà, il faudra un nouveau QR de l\'admin.',
          textAlign: TextAlign.center,
        ),
        actions: [
          FilledButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  Future<void> _showErrorDialog(String code) {
    final expired = code == TrailUnlockService.expiredQrErrorCode;
    return showDialog<void>(
      context: context,
      builder: (ctx) => AlertDialog(
        icon: Icon(
          expired ? Icons.timer_off : Icons.gpp_bad,
          color: const Color(0xFFD54A3A),
          size: 40,
        ),
        title: Text(expired ? 'QR code expiré' : 'Sentier non autorisé'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              expired
                  ? 'Ce QR code a plus de 24 heures et n\'est plus valide. '
                      'Demandez un nouveau code au guide, ou contactez '
                      'l\'administrateur.'
                  : 'Ce QR code est invalide ou non reconnu. Ce sentier ne peut '
                      'pas être ouvert. Veuillez contacter l\'administrateur.',
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 14),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: const Color(0xFFD54A3A).withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(10),
              ),
              child: Text(
                'Code d\'erreur : $code',
                style: const TextStyle(
                  fontWeight: FontWeight.w800,
                  color: Color(0xFFD54A3A),
                ),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Réessayer'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        title: const Text('Déverrouiller un sentier'),
        actions: [
          IconButton(
            tooltip: 'Lampe',
            icon: const Icon(Icons.flash_on),
            onPressed: () => _controller.toggleTorch(),
          ),
          IconButton(
            tooltip: 'Caméra',
            icon: const Icon(Icons.cameraswitch),
            onPressed: () => _controller.switchCamera(),
          ),
        ],
      ),
      body: Stack(
        children: [
          MobileScanner(
            controller: _controller,
            onDetect: _onDetect,
          ),
          // Framing overlay
          Center(
            child: Container(
              width: 250,
              height: 250,
              decoration: BoxDecoration(
                border: Border.all(color: Colors.white, width: 3),
                borderRadius: BorderRadius.circular(20),
              ),
            ),
          ),
          Positioned(
            left: 24,
            right: 24,
            bottom: 48,
            child: Container(
              padding: const EdgeInsets.all(14),
              decoration: BoxDecoration(
                color: Colors.black.withValues(alpha: 0.6),
                borderRadius: BorderRadius.circular(14),
              ),
              child: const Text(
                'Scannez le QR code du sentier affiché dans l\'application GeoTracker '
                'pour activer le bouton « Démarrer ».',
                textAlign: TextAlign.center,
                style: TextStyle(color: Colors.white, fontSize: 13, height: 1.4),
              ),
            ),
          ),
          if (_handling)
            const Center(child: CircularProgressIndicator(color: Colors.white)),
          if (_startError != null)
            Center(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(Icons.no_photography,
                        color: Colors.white70, size: 56),
                    const SizedBox(height: 16),
                    Text(
                      _startError!,
                      textAlign: TextAlign.center,
                      style: const TextStyle(color: Colors.white, fontSize: 14),
                    ),
                    const SizedBox(height: 16),
                    FilledButton.icon(
                      onPressed: _start,
                      icon: const Icon(Icons.refresh),
                      label: const Text('Réessayer'),
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }
}
